/**
 * Phase Manager
 * 
 * Manages phase lifecycle and persistence.
 * Integrates with Maskweaver's context module for file tracking.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { WeavePhase, WeavePlan, PhaseStatus } from './types.js';
import { yamlEscapeString, safeWriteFile, safeReadYaml, validatePlanStructure, repairAllPlans } from './yaml-repair.js';
import type { RepairResult } from './yaml-repair.js';

// ============================================================================
// Configuration
// ============================================================================

const WEAVE_DIR = '.opencode/weave';
const PLAN_FILE = 'PLAN.yaml';
const STATE_FILE = 'state.yaml';
const PLANS_DIR = 'plans';

function getWeaveDir(basePath: string = process.cwd()): string {
    return path.join(basePath, WEAVE_DIR);
}

function getPlanPath(basePath: string = process.cwd()): string {
    return path.join(getWeaveDir(basePath), PLAN_FILE);
}

function getStatePath(basePath: string = process.cwd()): string {
    return path.join(getWeaveDir(basePath), STATE_FILE);
}

function getPlansDir(basePath: string = process.cwd()): string {
    return path.join(getWeaveDir(basePath), PLANS_DIR);
}

function ensureWeaveDir(basePath: string = process.cwd()): void {
    const dir = getWeaveDir(basePath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

function ensurePlansDir(basePath: string = process.cwd()): void {
    const dir = getPlansDir(basePath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

// ============================================================================
// YAML Serialization (Safe - with proper escaping)
// ============================================================================

function serializePlan(plan: WeavePlan): string {
    const lines: string[] = [];

    lines.push(`# Weave Plan - ${plan.projectName}`);
    lines.push(`# Generated by Maskweaver Weave`);
    lines.push('');
    if (plan.planName) {
        lines.push(`plan_name: ${yamlEscapeString(plan.planName)}`);
    }
    lines.push(`project_name: ${yamlEscapeString(plan.projectName)}`);
    lines.push(`created_at: ${yamlEscapeString(plan.createdAt)}`);
    lines.push(`updated_at: ${yamlEscapeString(plan.updatedAt)}`);
    lines.push('');
    lines.push('vision: |');
    for (const line of plan.vision.split('\n')) {
        lines.push(`  ${line}`);
    }
    lines.push('');
    lines.push('architecture:');
    if (plan.architecture.frontend) lines.push(`  frontend: ${yamlEscapeString(plan.architecture.frontend)}`);
    if (plan.architecture.backend) lines.push(`  backend: ${yamlEscapeString(plan.architecture.backend)}`);
    if (plan.architecture.database) lines.push(`  database: ${yamlEscapeString(plan.architecture.database)}`);
    if (plan.architecture.notes) lines.push(`  notes: ${yamlEscapeString(plan.architecture.notes)}`);
    lines.push('');

    if (plan.researchPath) {
        lines.push(`research_path: ${yamlEscapeString(plan.researchPath)}`);
    }
    if (plan.researchUpdatedAt) {
        lines.push(`research_updated_at: ${yamlEscapeString(plan.researchUpdatedAt)}`);
    }
    if (typeof plan.planApproved === 'boolean') {
        lines.push(`plan_approved: ${plan.planApproved ? 'true' : 'false'}`);
    }
    if (plan.planApprovedAt) {
        lines.push(`plan_approved_at: ${yamlEscapeString(plan.planApprovedAt)}`);
    }
    if (plan.planApprovalNotes) {
        lines.push(`plan_approval_notes: ${yamlEscapeString(plan.planApprovalNotes)}`);
    }
    if (
        plan.researchPath
        || plan.researchUpdatedAt
        || typeof plan.planApproved === 'boolean'
        || plan.planApprovedAt
        || plan.planApprovalNotes
    ) {
        lines.push('');
    }

    if (plan.currentPhase) {
        lines.push(`current_phase: ${yamlEscapeString(plan.currentPhase)}`);
        lines.push('');
    }

    lines.push('phases:');
    for (const phase of plan.phases) {
        lines.push(`  - id: ${yamlEscapeString(phase.id)}`);
        lines.push(`    name: ${yamlEscapeString(phase.name)}`);
        lines.push(`    status: ${yamlEscapeString(phase.status)}`);
        lines.push(`    done_when: ${yamlEscapeString(phase.doneWhen)}`);

        if (phase.estimatedHours) {
            lines.push(`    estimated_hours: ${phase.estimatedHours}`);
        }
        if (phase.actualHours) {
            lines.push(`    actual_hours: ${phase.actualHours}`);
        }
        if (phase.startedAt) {
            lines.push(`    started_at: ${yamlEscapeString(phase.startedAt)}`);
        }
        if (phase.completedAt) {
            lines.push(`    completed_at: ${yamlEscapeString(phase.completedAt)}`);
        }

        lines.push('    checklist:');
        for (const item of phase.checklist) {
            lines.push(`      - ${yamlEscapeString(item)}`);
        }

        lines.push('    tasks:');
        for (const task of phase.tasks) {
            lines.push(`      - id: ${yamlEscapeString(task.id)}`);
            lines.push(`        name: ${yamlEscapeString(task.name)}`);
            lines.push(`        status: ${yamlEscapeString(task.status)}`);
            lines.push(`        retry_count: ${task.retryCount}`);
            lines.push(`        max_retries: ${task.maxRetries}`);
            if (task.testCase) {
                lines.push(`        test_case: ${yamlEscapeString(task.testCase)}`);
            }
            if (task.maskUsed) {
                lines.push(`        mask_used: ${yamlEscapeString(task.maskUsed)}`);
            }
            if (task.lastError) {
                lines.push(`        last_error: ${yamlEscapeString(task.lastError)}`);
            }
        }

        if (phase.dependsOn && phase.dependsOn.length > 0) {
            lines.push(`    depends_on: [${phase.dependsOn.map(d => yamlEscapeString(d)).join(', ')}]`);
        }

        if (phase.masksUsed && phase.masksUsed.length > 0) {
            lines.push(`    masks_used: [${phase.masksUsed.map(m => yamlEscapeString(m)).join(', ')}]`);
        }

        lines.push('');
    }

    return lines.join('\n');
}

// ============================================================================
// Phase Manager Class
// ============================================================================

export class PhaseManager {
    private basePath: string;
    private plan: WeavePlan | null = null;
    private _recoveryMessages: string[] = [];

    constructor(basePath: string = process.cwd()) {
        this.basePath = basePath;
    }

    /**
     * Get recovery messages from last load operation.
     * UI can display these to inform the user about auto-repairs.
     */
    getRecoveryMessages(): string[] {
        return this._recoveryMessages;
    }

    /**
     * Load existing plan or return null.
     * Supports multi-plan architecture (state.yaml → plans/) with legacy PLAN.yaml fallback.
     * Auto-repairs corrupted YAML files when possible.
     */
    async loadPlan(): Promise<WeavePlan | null> {
        this._recoveryMessages = [];

        // 1. Try new multi-plan architecture: state.yaml → plans/{active_plan}.yaml
        const statePath = getStatePath(this.basePath);
        if (fs.existsSync(statePath)) {
            try {
                const stateResult = await safeReadYaml(statePath);
                if (stateResult.repaired) {
                    this._recoveryMessages.push(`state.yaml was auto-repaired: ${stateResult.changes?.join(', ')}`);
                }
                
                const state = stateResult.data;
                const activePlan = state?.active_plan;

                if (activePlan) {
                    const planFilePath = path.join(getPlansDir(this.basePath), `${activePlan}.yaml`);
                    if (fs.existsSync(planFilePath)) {
                        const result = await safeReadYaml(planFilePath);
                        
                        if (result.repaired) {
                            this._recoveryMessages.push(
                                `${activePlan}.yaml was auto-repaired: ${result.changes?.join(', ')}`
                            );
                        }
                        
                        if (result.data) {
                            const validated = validatePlanStructure(result.data);
                            this.plan = this.rawToPlan(validated);
                            return this.plan;
                        } else if (result.error) {
                            console.error(`[PhaseManager] ${result.error}`);
                            this._recoveryMessages.push(result.error);
                        }
                    }
                }
            } catch (e) {
                console.error('[PhaseManager] Failed to load from state.yaml:', e);
            }
        }

        // 2. Legacy fallback: PLAN.yaml
        const planPath = getPlanPath(this.basePath);
        if (!fs.existsSync(planPath)) {
            return null;
        }

        const result = await safeReadYaml(planPath);
        
        if (result.repaired) {
            this._recoveryMessages.push(
                `PLAN.yaml was auto-repaired: ${result.changes?.join(', ')}`
            );
        }
        
        if (result.data) {
            const validated = validatePlanStructure(result.data);
            this.plan = this.rawToPlan(validated);
            return this.plan;
        }
        
        if (result.error) {
            console.error(`[PhaseManager] ${result.error}`);
            this._recoveryMessages.push(result.error);
        }
        
        return null;
    }

    /**
     * Save plan to disk using safe file I/O (atomic writes with backup).
     * If state.yaml exists (new mode): save to plans/{planName}.yaml and update state.yaml.
     * Otherwise (legacy mode): save to PLAN.yaml.
     */
    async savePlan(plan: WeavePlan): Promise<void> {
        ensureWeaveDir(this.basePath);

        plan.updatedAt = new Date().toISOString();
        const content = serializePlan(plan);

        const statePath = getStatePath(this.basePath);
        // vNext default: always use multi-plan mode. If state.yaml is missing,
        // create it instead of falling back to legacy PLAN.yaml.
        if (!fs.existsSync(statePath)) {
            ensurePlansDir(this.basePath);
            const { stringify } = await import('yaml');
            safeWriteFile(statePath, stringify({ active_plan: null }));
        }

        // Multi-plan mode: save to plans/ directory
        ensurePlansDir(this.basePath);
        const planName = this.toPlanFileName(plan.planName || plan.projectName);
        // Persist normalized planName back onto the plan for stability
        plan.planName = planName;
        const planFilePath = path.join(getPlansDir(this.basePath), `${planName}.yaml`);
        safeWriteFile(planFilePath, content);

        // Update state.yaml with active_plan while preserving additional keys.
        // This avoids clobbering forward-compatible state fields.
        const { stringify } = await import('yaml');
        let stateData: Record<string, any> = {};
        try {
            const stateResult = await safeReadYaml(statePath);
            if (stateResult.data && typeof stateResult.data === 'object') {
                stateData = { ...stateResult.data };
            }
        } catch {
            // ignore state parse errors and overwrite with minimal state
        }

        stateData.active_plan = planName;
        const stateContent = stringify(stateData);
        safeWriteFile(statePath, stateContent);

        this.plan = plan;
    }

    /**
     * Repair all plan files. Returns repair report.
     */
    async repairPlans(): Promise<{ results: RepairResult[]; summary: string }> {
        return repairAllPlans(this.basePath);
    }

    /**
     * Create a new plan.
     */
    async createPlan(input: {
        planName?: string;
        projectName: string;
        vision: string;
        architecture: WeavePlan['architecture'];
        phases: Omit<WeavePhase, 'tasks'>[];
    }): Promise<WeavePlan> {
        const now = new Date().toISOString();

        const plan: WeavePlan = {
            planName: input.planName,
            projectName: input.projectName,
            createdAt: now,
            updatedAt: now,
            vision: input.vision,
            architecture: input.architecture,
            planApproved: false,
            phases: input.phases.map(p => ({
                ...p,
                tasks: [],
            })),
        };

        await this.savePlan(plan);
        return plan;
    }

    /**
     * Get a specific phase.
     */
    getPhase(phaseId: string): WeavePhase | null {
        if (!this.plan) return null;
        return this.plan.phases.find(p => p.id === phaseId) || null;
    }

    /**
     * Update phase status.
     */
    async updatePhaseStatus(
        phaseId: string,
        status: PhaseStatus,
        additionalData?: Partial<WeavePhase>
    ): Promise<WeavePhase | null> {
        if (!this.plan) {
            await this.loadPlan();
        }

        if (!this.plan) return null;

        const phase = this.plan.phases.find(p => p.id === phaseId);
        if (!phase) return null;

        phase.status = status;

        if (status === 'in_progress' && !phase.startedAt) {
            phase.startedAt = new Date().toISOString();
        }

        if (status === 'completed' && !phase.completedAt) {
            phase.completedAt = new Date().toISOString();

            // Calculate actual hours if we have start time
            if (phase.startedAt) {
                const start = new Date(phase.startedAt).getTime();
                const end = new Date(phase.completedAt).getTime();
                phase.actualHours = Math.round((end - start) / (1000 * 60 * 60) * 10) / 10;
            }
        }

        if (additionalData) {
            Object.assign(phase, additionalData);
        }

        this.plan.currentPhase = status === 'in_progress' ? phaseId : undefined;
        await this.savePlan(this.plan);

        return phase;
    }

    /**
     * Add tasks to a phase.
     */
    async addTasks(phaseId: string, tasks: Omit<WeavePhase['tasks'][0], 'status' | 'retryCount'>[]): Promise<void> {
        if (!this.plan) {
            await this.loadPlan();
        }

        if (!this.plan) return;

        const phase = this.plan.phases.find(p => p.id === phaseId);
        if (!phase) return;

        phase.tasks.push(...tasks.map(t => ({
            ...t,
            status: 'pending' as const,
            retryCount: 0,
            maxRetries: t.maxRetries ?? 5,
        })));

        await this.savePlan(this.plan);
    }

    /**
     * Update task status.
     */
    async updateTaskStatus(
        phaseId: string,
        taskId: string,
        status: 'pending' | 'in_progress' | 'passed' | 'failed',
        additionalData?: Partial<WeavePhase['tasks'][0]>
    ): Promise<void> {
        if (!this.plan) {
            await this.loadPlan();
        }

        if (!this.plan) return;

        const phase = this.plan.phases.find(p => p.id === phaseId);
        if (!phase) return;

        const task = phase.tasks.find(t => t.id === taskId);
        if (!task) return;

        task.status = status;

        if (status === 'failed') {
            task.retryCount++;
        }

        if (additionalData) {
            Object.assign(task, additionalData);
        }

        // Track masks used in phase
        if (task.maskUsed && !phase.masksUsed?.includes(task.maskUsed)) {
            phase.masksUsed = [...(phase.masksUsed || []), task.maskUsed];
        }

        await this.savePlan(this.plan);
    }

    /**
     * Mark all tasks in a phase as passed.
     * Useful when the phase is approved after full verification.
     */
    async markAllTasksPassed(phaseId: string): Promise<void> {
        if (!this.plan) {
            await this.loadPlan();
        }

        if (!this.plan) return;

        const phase = this.plan.phases.find(p => p.id === phaseId);
        if (!phase) return;

        if (!phase.tasks || phase.tasks.length === 0) return;

        for (const task of phase.tasks) {
            task.status = 'passed';
        }

        await this.savePlan(this.plan);
    }

    /**
     * Get next pending phase (respecting dependencies).
     */
    getNextPhase(): WeavePhase | null {
        if (!this.plan) return null;

        for (const phase of this.plan.phases) {
            if (phase.status === 'pending') {
                // Check dependencies
                if (phase.dependsOn && phase.dependsOn.length > 0) {
                    const allDepsCompleted = phase.dependsOn.every(depId => {
                        const dep = this.plan!.phases.find(p => p.id === depId);
                        return dep?.status === 'completed';
                    });

                    if (!allDepsCompleted) continue;
                }

                return phase;
            }
        }

        return null;
    }

    /**
     * Get plan statistics.
     */
    getStats(): {
        totalPhases: number;
        completedPhases: number;
        inProgressPhases: number;
        progress: number;
    } {
        if (!this.plan) {
            return { totalPhases: 0, completedPhases: 0, inProgressPhases: 0, progress: 0 };
        }

        const total = this.plan.phases.length;
        const completed = this.plan.phases.filter(p => p.status === 'completed').length;
        const inProgress = this.plan.phases.filter(p => p.status === 'in_progress').length;

        return {
            totalPhases: total,
            completedPhases: completed,
            inProgressPhases: inProgress,
            progress: total > 0 ? Math.round((completed / total) * 100) : 0,
        };
    }

    /**
     * Convert project name to a filesystem-safe plan file name.
     */
    private toPlanFileName(projectName: string): string {
        return projectName
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '') || 'unnamed';
    }

    /**
     * Load all plans from the plans/ directory.
     * Returns empty array in legacy mode or if no plans exist.
     * Auto-repairs corrupted plans when possible.
     */
    async loadAllPlans(): Promise<WeavePlan[]> {
        const plansDir = getPlansDir(this.basePath);
        if (!fs.existsSync(plansDir)) {
            // Legacy mode: try loading single PLAN.yaml
            const legacyPlan = await this.loadPlan();
            return legacyPlan ? [legacyPlan] : [];
        }

        const plans: WeavePlan[] = [];

        try {
            const files = fs.readdirSync(plansDir).filter(f => f.endsWith('.yaml'));
            for (const file of files) {
                const filePath = path.join(plansDir, file);
                const result = await safeReadYaml(filePath);
                
                if (result.repaired) {
                    this._recoveryMessages.push(
                        `${file} was auto-repaired: ${result.changes?.join(', ')}`
                    );
                }
                
                if (result.data) {
                    const validated = validatePlanStructure(result.data);
                    if (validated) {
                        plans.push(this.rawToPlan(validated));
                    }
                } else if (result.error) {
                    console.error(`[PhaseManager] Skipping unrecoverable plan ${file}: ${result.error}`);
                    this._recoveryMessages.push(
                        `Skipping unrecoverable plan ${file}: ${result.error}`
                    );
                }
            }
        } catch (e) {
            console.error('[PhaseManager] Failed to scan plans directory:', e);
        }

        return plans;
    }

    /**
     * Get the active plan name from state.yaml.
     * Returns null in legacy mode or if state.yaml doesn't exist.
     */
    async getActivePlanName(): Promise<string | null> {
        const statePath = getStatePath(this.basePath);
        if (!fs.existsSync(statePath)) {
            return null;
        }

        const result = await safeReadYaml(statePath);
        return result.data?.active_plan || null;
    }

    /**
     * Load and return state.yaml content.
     * Returns null if state.yaml doesn't exist (legacy mode).
     */
    async loadState(): Promise<{ active_plan?: string } | null> {
        const statePath = getStatePath(this.basePath);
        if (!fs.existsSync(statePath)) {
            return null;
        }

        const result = await safeReadYaml(statePath);
        return result.data || null;
    }

    private rawToPlan(raw: any): WeavePlan {
        return {
            planName: raw.plan_name || raw.planName,
            projectName: raw.project_name || raw.projectName || 'Unknown',
            createdAt: raw.created_at || raw.createdAt || new Date().toISOString(),
            updatedAt: raw.updated_at || raw.updatedAt || new Date().toISOString(),
            vision: raw.vision || '',
            architecture: raw.architecture || {},
            researchPath: raw.research_path || raw.researchPath,
            researchUpdatedAt: raw.research_updated_at || raw.researchUpdatedAt,
            planApproved: typeof raw.plan_approved === 'boolean'
                ? raw.plan_approved
                : (typeof raw.planApproved === 'boolean' ? raw.planApproved : undefined),
            planApprovedAt: raw.plan_approved_at || raw.planApprovedAt,
            planApprovalNotes: raw.plan_approval_notes || raw.planApprovalNotes,
            currentPhase: raw.current_phase || raw.currentPhase,
            phases: (raw.phases || []).map((p: any) => ({
                id: p.id,
                name: p.name,
                status: p.status || 'pending',
                doneWhen: p.done_when || p.doneWhen || '',
                checklist: p.checklist || [],
                tasks: (p.tasks || []).map((t: any) => ({
                    id: t.id,
                    name: t.name,
                    status: t.status || 'pending',
                    testCase: t.test_case || t.testCase,
                    retryCount: t.retry_count || t.retryCount || 0,
                    maxRetries: t.max_retries || t.maxRetries || 5,
                    lastError: t.last_error || t.lastError,
                    maskUsed: t.mask_used || t.maskUsed,
                })),
                dependsOn: p.depends_on || p.dependsOn,
                estimatedHours: p.estimated_hours || p.estimatedHours,
                actualHours: p.actual_hours || p.actualHours,
                startedAt: p.started_at || p.startedAt,
                completedAt: p.completed_at || p.completedAt,
                masksUsed: p.masks_used || p.masksUsed,
            })),
        };
    }
}

// ============================================================================
// Convenience Functions
// ============================================================================

const managerCache = new Map<string, PhaseManager>();

function normalizeBasePath(basePath?: string): string {
    return path.resolve(basePath || process.cwd());
}

export function getPhaseManager(basePath?: string): PhaseManager {
    const key = normalizeBasePath(basePath);
    const cached = managerCache.get(key);
    if (cached) return cached;

    const manager = new PhaseManager(key);
    managerCache.set(key, manager);
    return manager;
}

export async function createPhase(
    phaseId: string,
    name: string,
    doneWhen: string,
    checklist: string[],
    dependsOn?: string[]
): Promise<WeavePhase> {
    const phase: WeavePhase = {
        id: phaseId,
        name,
        status: 'pending',
        doneWhen,
        checklist,
        tasks: [],
        dependsOn,
    };
    return phase;
}

export async function getPhase(phaseId: string): Promise<WeavePhase | null> {
    const manager = getPhaseManager();
    await manager.loadPlan();
    return manager.getPhase(phaseId);
}

export async function updatePhaseStatus(
    phaseId: string,
    status: PhaseStatus
): Promise<WeavePhase | null> {
    const manager = getPhaseManager();
    return manager.updatePhaseStatus(phaseId, status);
}

export async function listPhases(): Promise<WeavePhase[]> {
    const manager = getPhaseManager();
    const plan = await manager.loadPlan();
    return plan?.phases || [];
}
