/**
 * Phase Manager
 * 
 * Manages phase lifecycle and persistence.
 * Integrates with Maskweaver's context module for file tracking.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { WeavePhase, WeavePlan, PhaseStatus } from './types.js';

// ============================================================================
// Configuration
// ============================================================================

const WEAVE_DIR = '.opencode/weave';
const PLAN_FILE = 'PLAN.yaml';
const STATE_FILE = 'state.yaml';
const PLANS_DIR = 'plans';

function getWeaveDir(basePath: string = process.cwd()): string {
    return path.join(basePath, WEAVE_DIR);
}

function getPlanPath(basePath: string = process.cwd()): string {
    return path.join(getWeaveDir(basePath), PLAN_FILE);
}

function getStatePath(basePath: string = process.cwd()): string {
    return path.join(getWeaveDir(basePath), STATE_FILE);
}

function getPlansDir(basePath: string = process.cwd()): string {
    return path.join(getWeaveDir(basePath), PLANS_DIR);
}

function ensureWeaveDir(basePath: string = process.cwd()): void {
    const dir = getWeaveDir(basePath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

function ensurePlansDir(basePath: string = process.cwd()): void {
    const dir = getPlansDir(basePath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

// ============================================================================
// YAML Serialization (Simple)
// ============================================================================

function serializePlan(plan: WeavePlan): string {
    const lines: string[] = [];

    lines.push(`# Weave Plan - ${plan.projectName}`);
    lines.push(`# Generated by Maskweaver Weave`);
    lines.push('');
    lines.push(`project_name: "${plan.projectName}"`);
    lines.push(`created_at: "${plan.createdAt}"`);
    lines.push(`updated_at: "${plan.updatedAt}"`);
    lines.push('');
    lines.push('vision: |');
    for (const line of plan.vision.split('\n')) {
        lines.push(`  ${line}`);
    }
    lines.push('');
    lines.push('architecture:');
    if (plan.architecture.frontend) lines.push(`  frontend: "${plan.architecture.frontend}"`);
    if (plan.architecture.backend) lines.push(`  backend: "${plan.architecture.backend}"`);
    if (plan.architecture.database) lines.push(`  database: "${plan.architecture.database}"`);
    if (plan.architecture.notes) lines.push(`  notes: "${plan.architecture.notes}"`);
    lines.push('');

    if (plan.currentPhase) {
        lines.push(`current_phase: "${plan.currentPhase}"`);
        lines.push('');
    }

    lines.push('phases:');
    for (const phase of plan.phases) {
        lines.push(`  - id: "${phase.id}"`);
        lines.push(`    name: "${phase.name}"`);
        lines.push(`    status: "${phase.status}"`);
        lines.push(`    done_when: "${phase.doneWhen}"`);

        if (phase.estimatedHours) {
            lines.push(`    estimated_hours: ${phase.estimatedHours}`);
        }
        if (phase.actualHours) {
            lines.push(`    actual_hours: ${phase.actualHours}`);
        }
        if (phase.startedAt) {
            lines.push(`    started_at: "${phase.startedAt}"`);
        }
        if (phase.completedAt) {
            lines.push(`    completed_at: "${phase.completedAt}"`);
        }

        lines.push('    checklist:');
        for (const item of phase.checklist) {
            lines.push(`      - "${item}"`);
        }

        lines.push('    tasks:');
        for (const task of phase.tasks) {
            lines.push(`      - id: "${task.id}"`);
            lines.push(`        name: "${task.name}"`);
            lines.push(`        status: "${task.status}"`);
            lines.push(`        retry_count: ${task.retryCount}`);
            lines.push(`        max_retries: ${task.maxRetries}`);
            if (task.testCase) {
                lines.push(`        test_case: "${task.testCase}"`);
            }
            if (task.maskUsed) {
                lines.push(`        mask_used: "${task.maskUsed}"`);
            }
            if (task.lastError) {
                lines.push(`        last_error: "${task.lastError.replace(/"/g, '\\"')}"`);
            }
        }

        if (phase.dependsOn && phase.dependsOn.length > 0) {
            lines.push(`    depends_on: [${phase.dependsOn.map(d => `"${d}"`).join(', ')}]`);
        }

        if (phase.masksUsed && phase.masksUsed.length > 0) {
            lines.push(`    masks_used: [${phase.masksUsed.map(m => `"${m}"`).join(', ')}]`);
        }

        lines.push('');
    }

    return lines.join('\n');
}

// ============================================================================
// Phase Manager Class
// ============================================================================

export class PhaseManager {
    private basePath: string;
    private plan: WeavePlan | null = null;

    constructor(basePath: string = process.cwd()) {
        this.basePath = basePath;
    }

    /**
     * Load existing plan or return null.
     * Supports multi-plan architecture (state.yaml → plans/) with legacy PLAN.yaml fallback.
     */
    async loadPlan(): Promise<WeavePlan | null> {
        const { parse } = await import('yaml');

        // 1. Try new multi-plan architecture: state.yaml → plans/{active_plan}.yaml
        const statePath = getStatePath(this.basePath);
        if (fs.existsSync(statePath)) {
            try {
                const stateContent = fs.readFileSync(statePath, 'utf-8');
                const state = parse(stateContent);
                const activePlan = state?.active_plan;

                if (activePlan) {
                    const planFilePath = path.join(getPlansDir(this.basePath), `${activePlan}.yaml`);
                    if (fs.existsSync(planFilePath)) {
                        const content = fs.readFileSync(planFilePath, 'utf-8');
                        const raw = parse(content);
                        this.plan = this.rawToPlan(raw);
                        return this.plan;
                    }
                }
            } catch (e) {
                console.error('[PhaseManager] Failed to load from state.yaml:', e);
            }
        }

        // 2. Legacy fallback: PLAN.yaml
        const planPath = getPlanPath(this.basePath);
        if (!fs.existsSync(planPath)) {
            return null;
        }

        try {
            const content = fs.readFileSync(planPath, 'utf-8');
            const raw = parse(content);

            this.plan = this.rawToPlan(raw);
            return this.plan;
        } catch (e) {
            console.error('[PhaseManager] Failed to load plan:', e);
            return null;
        }
    }

    /**
     * Save plan to disk.
     * If state.yaml exists (new mode): save to plans/{planName}.yaml and update state.yaml.
     * Otherwise (legacy mode): save to PLAN.yaml.
     */
    async savePlan(plan: WeavePlan): Promise<void> {
        ensureWeaveDir(this.basePath);
        const { stringify } = await import('yaml');

        plan.updatedAt = new Date().toISOString();
        const content = serializePlan(plan);

        const statePath = getStatePath(this.basePath);
        if (fs.existsSync(statePath)) {
            // New multi-plan mode: save to plans/ directory
            ensurePlansDir(this.basePath);
            const planName = this.toPlanFileName(plan.projectName);
            const planFilePath = path.join(getPlansDir(this.basePath), `${planName}.yaml`);
            fs.writeFileSync(planFilePath, content, 'utf-8');

            // Update state.yaml with active_plan
            const stateContent = stringify({ active_plan: planName });
            fs.writeFileSync(statePath, stateContent, 'utf-8');
        } else {
            // Legacy mode: save to PLAN.yaml
            fs.writeFileSync(getPlanPath(this.basePath), content, 'utf-8');
        }

        this.plan = plan;
    }

    /**
     * Create a new plan.
     */
    async createPlan(input: {
        projectName: string;
        vision: string;
        architecture: WeavePlan['architecture'];
        phases: Omit<WeavePhase, 'tasks'>[];
    }): Promise<WeavePlan> {
        const now = new Date().toISOString();

        const plan: WeavePlan = {
            projectName: input.projectName,
            createdAt: now,
            updatedAt: now,
            vision: input.vision,
            architecture: input.architecture,
            phases: input.phases.map(p => ({
                ...p,
                tasks: [],
            })),
        };

        await this.savePlan(plan);
        return plan;
    }

    /**
     * Get a specific phase.
     */
    getPhase(phaseId: string): WeavePhase | null {
        if (!this.plan) return null;
        return this.plan.phases.find(p => p.id === phaseId) || null;
    }

    /**
     * Update phase status.
     */
    async updatePhaseStatus(
        phaseId: string,
        status: PhaseStatus,
        additionalData?: Partial<WeavePhase>
    ): Promise<WeavePhase | null> {
        if (!this.plan) {
            await this.loadPlan();
        }

        if (!this.plan) return null;

        const phase = this.plan.phases.find(p => p.id === phaseId);
        if (!phase) return null;

        phase.status = status;

        if (status === 'in_progress' && !phase.startedAt) {
            phase.startedAt = new Date().toISOString();
        }

        if (status === 'completed' && !phase.completedAt) {
            phase.completedAt = new Date().toISOString();

            // Calculate actual hours if we have start time
            if (phase.startedAt) {
                const start = new Date(phase.startedAt).getTime();
                const end = new Date(phase.completedAt).getTime();
                phase.actualHours = Math.round((end - start) / (1000 * 60 * 60) * 10) / 10;
            }
        }

        if (additionalData) {
            Object.assign(phase, additionalData);
        }

        this.plan.currentPhase = status === 'in_progress' ? phaseId : undefined;
        await this.savePlan(this.plan);

        return phase;
    }

    /**
     * Add tasks to a phase.
     */
    async addTasks(phaseId: string, tasks: Omit<WeavePhase['tasks'][0], 'status' | 'retryCount'>[]): Promise<void> {
        if (!this.plan) {
            await this.loadPlan();
        }

        if (!this.plan) return;

        const phase = this.plan.phases.find(p => p.id === phaseId);
        if (!phase) return;

        phase.tasks.push(...tasks.map(t => ({
            ...t,
            status: 'pending' as const,
            retryCount: 0,
            maxRetries: t.maxRetries ?? 5,
        })));

        await this.savePlan(this.plan);
    }

    /**
     * Update task status.
     */
    async updateTaskStatus(
        phaseId: string,
        taskId: string,
        status: 'pending' | 'in_progress' | 'passed' | 'failed',
        additionalData?: Partial<WeavePhase['tasks'][0]>
    ): Promise<void> {
        if (!this.plan) {
            await this.loadPlan();
        }

        if (!this.plan) return;

        const phase = this.plan.phases.find(p => p.id === phaseId);
        if (!phase) return;

        const task = phase.tasks.find(t => t.id === taskId);
        if (!task) return;

        task.status = status;

        if (status === 'failed') {
            task.retryCount++;
        }

        if (additionalData) {
            Object.assign(task, additionalData);
        }

        // Track masks used in phase
        if (task.maskUsed && !phase.masksUsed?.includes(task.maskUsed)) {
            phase.masksUsed = [...(phase.masksUsed || []), task.maskUsed];
        }

        await this.savePlan(this.plan);
    }

    /**
     * Get next pending phase (respecting dependencies).
     */
    getNextPhase(): WeavePhase | null {
        if (!this.plan) return null;

        for (const phase of this.plan.phases) {
            if (phase.status === 'pending') {
                // Check dependencies
                if (phase.dependsOn && phase.dependsOn.length > 0) {
                    const allDepsCompleted = phase.dependsOn.every(depId => {
                        const dep = this.plan!.phases.find(p => p.id === depId);
                        return dep?.status === 'completed';
                    });

                    if (!allDepsCompleted) continue;
                }

                return phase;
            }
        }

        return null;
    }

    /**
     * Get plan statistics.
     */
    getStats(): {
        totalPhases: number;
        completedPhases: number;
        inProgressPhases: number;
        progress: number;
    } {
        if (!this.plan) {
            return { totalPhases: 0, completedPhases: 0, inProgressPhases: 0, progress: 0 };
        }

        const total = this.plan.phases.length;
        const completed = this.plan.phases.filter(p => p.status === 'completed').length;
        const inProgress = this.plan.phases.filter(p => p.status === 'in_progress').length;

        return {
            totalPhases: total,
            completedPhases: completed,
            inProgressPhases: inProgress,
            progress: total > 0 ? Math.round((completed / total) * 100) : 0,
        };
    }

    /**
     * Convert project name to a filesystem-safe plan file name.
     */
    private toPlanFileName(projectName: string): string {
        return projectName
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '') || 'unnamed';
    }

    /**
     * Load all plans from the plans/ directory.
     * Returns empty array in legacy mode or if no plans exist.
     */
    async loadAllPlans(): Promise<WeavePlan[]> {
        const plansDir = getPlansDir(this.basePath);
        if (!fs.existsSync(plansDir)) {
            // Legacy mode: try loading single PLAN.yaml
            const legacyPlan = await this.loadPlan();
            return legacyPlan ? [legacyPlan] : [];
        }

        const { parse } = await import('yaml');
        const plans: WeavePlan[] = [];

        try {
            const files = fs.readdirSync(plansDir).filter(f => f.endsWith('.yaml'));
            for (const file of files) {
                try {
                    const content = fs.readFileSync(path.join(plansDir, file), 'utf-8');
                    const raw = parse(content);
                    plans.push(this.rawToPlan(raw));
                } catch (e) {
                    console.error(`[PhaseManager] Failed to load plan ${file}:`, e);
                }
            }
        } catch (e) {
            console.error('[PhaseManager] Failed to scan plans directory:', e);
        }

        return plans;
    }

    /**
     * Get the active plan name from state.yaml.
     * Returns null in legacy mode or if state.yaml doesn't exist.
     */
    async getActivePlanName(): Promise<string | null> {
        const statePath = getStatePath(this.basePath);
        if (!fs.existsSync(statePath)) {
            return null;
        }

        try {
            const { parse } = await import('yaml');
            const content = fs.readFileSync(statePath, 'utf-8');
            const state = parse(content);
            return state?.active_plan || null;
        } catch (e) {
            console.error('[PhaseManager] Failed to read state.yaml:', e);
            return null;
        }
    }

    /**
     * Load and return state.yaml content.
     * Returns null if state.yaml doesn't exist (legacy mode).
     */
    async loadState(): Promise<{ active_plan?: string } | null> {
        const statePath = getStatePath(this.basePath);
        if (!fs.existsSync(statePath)) {
            return null;
        }

        try {
            const { parse } = await import('yaml');
            const content = fs.readFileSync(statePath, 'utf-8');
            return parse(content) || null;
        } catch (e) {
            console.error('[PhaseManager] Failed to load state.yaml:', e);
            return null;
        }
    }

    private rawToPlan(raw: any): WeavePlan {
        return {
            projectName: raw.project_name || raw.projectName || 'Unknown',
            createdAt: raw.created_at || raw.createdAt || new Date().toISOString(),
            updatedAt: raw.updated_at || raw.updatedAt || new Date().toISOString(),
            vision: raw.vision || '',
            architecture: raw.architecture || {},
            currentPhase: raw.current_phase || raw.currentPhase,
            phases: (raw.phases || []).map((p: any) => ({
                id: p.id,
                name: p.name,
                status: p.status || 'pending',
                doneWhen: p.done_when || p.doneWhen || '',
                checklist: p.checklist || [],
                tasks: (p.tasks || []).map((t: any) => ({
                    id: t.id,
                    name: t.name,
                    status: t.status || 'pending',
                    testCase: t.test_case || t.testCase,
                    retryCount: t.retry_count || t.retryCount || 0,
                    maxRetries: t.max_retries || t.maxRetries || 5,
                    lastError: t.last_error || t.lastError,
                    maskUsed: t.mask_used || t.maskUsed,
                })),
                dependsOn: p.depends_on || p.dependsOn,
                estimatedHours: p.estimated_hours || p.estimatedHours,
                actualHours: p.actual_hours || p.actualHours,
                startedAt: p.started_at || p.startedAt,
                completedAt: p.completed_at || p.completedAt,
                masksUsed: p.masks_used || p.masksUsed,
            })),
        };
    }
}

// ============================================================================
// Convenience Functions
// ============================================================================

let managerInstance: PhaseManager | null = null;

export function getPhaseManager(basePath?: string): PhaseManager {
    if (!managerInstance || basePath) {
        managerInstance = new PhaseManager(basePath);
    }
    return managerInstance;
}

export async function createPhase(
    phaseId: string,
    name: string,
    doneWhen: string,
    checklist: string[],
    dependsOn?: string[]
): Promise<WeavePhase> {
    const phase: WeavePhase = {
        id: phaseId,
        name,
        status: 'pending',
        doneWhen,
        checklist,
        tasks: [],
        dependsOn,
    };
    return phase;
}

export async function getPhase(phaseId: string): Promise<WeavePhase | null> {
    const manager = getPhaseManager();
    await manager.loadPlan();
    return manager.getPhase(phaseId);
}

export async function updatePhaseStatus(
    phaseId: string,
    status: PhaseStatus
): Promise<WeavePhase | null> {
    const manager = getPhaseManager();
    return manager.updatePhaseStatus(phaseId, status);
}

export async function listPhases(): Promise<WeavePhase[]> {
    const manager = getPhaseManager();
    const plan = await manager.loadPlan();
    return plan?.phases || [];
}
